CRITICAL - 2025-05-07 19:42:09 --> CodeIgniter\Router\Exceptions\RouterException: The namespace delimiter is a backslash (\), not a slash (/). Route handler: "\App\Controllers\alta/Alta::eleccionDarAlta"
[Method: GET, Route: seleccionAlta]
in SYSTEMPATH\Router\Router.php on line 496.
 1 SYSTEMPATH\Router\Router.php(496): CodeIgniter\Router\Exceptions\RouterException::forInvalidControllerName('\\App\\Controllers\\alta/Alta::eleccionDarAlta')
 2 SYSTEMPATH\Router\Router.php(213): CodeIgniter\Router\Router->checkRoutes('seleccionAlta')
 3 SYSTEMPATH\CodeIgniter.php(832): CodeIgniter\Router\Router->handle('seleccionAlta')
 4 SYSTEMPATH\CodeIgniter.php(455): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 19:42:36 --> CodeIgniter\Router\Exceptions\RouterException: The namespace delimiter is a backslash (\), not a slash (/). Route handler: "\App\Controllers\alta/Alta::eleccionDarAlta"
[Method: GET, Route: seleccionAlta]
in SYSTEMPATH\Router\Router.php on line 496.
 1 SYSTEMPATH\Router\Router.php(496): CodeIgniter\Router\Exceptions\RouterException::forInvalidControllerName('\\App\\Controllers\\alta/Alta::eleccionDarAlta')
 2 SYSTEMPATH\Router\Router.php(213): CodeIgniter\Router\Router->checkRoutes('seleccionAlta')
 3 SYSTEMPATH\CodeIgniter.php(832): CodeIgniter\Router\Router->handle('seleccionAlta')
 4 SYSTEMPATH\CodeIgniter.php(455): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 19:43:23 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "alta/eleccionDarAlta.php"
[Method: GET, Route: seleccionAlta]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('alta/eleccionDarAlta.php')
 2 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('alta/eleccionDarAlta', [], true)
 3 APPPATH\Controllers\Alta.php(11): view('alta/eleccionDarAlta')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Alta->seleccionAlta()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Alta))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 19:43:27 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "alta/eleccionDarAlta.php"
[Method: GET, Route: seleccionAlta]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('alta/eleccionDarAlta.php')
 2 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('alta/eleccionDarAlta', [], true)
 3 APPPATH\Controllers\Alta.php(11): view('alta/eleccionDarAlta')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Alta->seleccionAlta()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Alta))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 20:18:25 --> Error: Call to undefined function form_open()
[Method: GET, Route: pantallaAmoAlta]
in APPPATH\Views\alta\amoAlta.php on line 5.
 1 SYSTEMPATH\View\View.php(224): include()
 2 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('alta/amoAlta', [], true)
 4 APPPATH\Controllers\Alta.php(16): view('alta/amoAlta')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Alta->pantallaAmoAlta()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Alta))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 20:18:34 --> Error: Call to undefined function form_open()
[Method: GET, Route: pantallaAmoAlta]
in APPPATH\Views\alta\amoAlta.php on line 5.
 1 SYSTEMPATH\View\View.php(224): include()
 2 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('alta/amoAlta', [], true)
 4 APPPATH\Controllers\Alta.php(16): view('alta/amoAlta')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Alta->pantallaAmoAlta()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Alta))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-07 22:17:40 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\Proyecto_Topicos\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\Proyecto_Topicos\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\Proyecto_Topicos\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Proyecto_Topicos\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Proyecto_Topicos\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `am...', Array, false)
#4 C:\xampp\htdocs\Proyecto_Topicos\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Proyecto_Topicos\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Proyecto_Topicos\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Proyecto_Topicos\app\Models\AmoModel.php(19): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\Proyecto_Topicos\app\Controllers\Alta.php(48): App\Models\AmoModel->insertarAmo(Array)
#9 C:\xampp\htdocs\Proyecto_Topicos\system\CodeIgniter.php(933): App\Controllers\Alta->insertarAmo()
#10 C:\xampp\htdocs\Proyecto_Topicos\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Alta))
#11 C:\xampp\htdocs\Proyecto_Topicos\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\Proyecto_Topicos\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\Proyecto_Topicos\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\Proyecto_Topicos\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\Proyecto_Topicos\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\Proyecto_Topicos\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Proyecto_Topicos\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Proyecto_Topicos\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `am...', Array, false)
#3 C:\xampp\htdocs\Proyecto_Topicos\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\Proyecto_Topicos\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\Proyecto_Topicos\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp\htdocs\Proyecto_Topicos\app\Models\AmoModel.php(19): CodeIgniter\Model->insert(Array)
#7 C:\xampp\htdocs\Proyecto_Topicos\app\Controllers\Alta.php(48): App\Models\AmoModel->insertarAmo(Array)
#8 C:\xampp\htdocs\Proyecto_Topicos\system\CodeIgniter.php(933): App\Controllers\Alta->insertarAmo()
#9 C:\xampp\htdocs\Proyecto_Topicos\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Alta))
#10 C:\xampp\htdocs\Proyecto_Topicos\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Proyecto_Topicos\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Proyecto_Topicos\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\Proyecto_Topicos\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-05-07 22:17:40 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: POST, Route: insertarAmo]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `amos` (`nombre`, `direccion`, `telefono`, `fechaAlta`) VALUES (:nombre:, :direccion:, :telefono:, :fechaAlta:)', [...], false)
 3 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Models\AmoModel.php(19): CodeIgniter\Model->insert([...])
 7 APPPATH\Controllers\Alta.php(48): App\Models\AmoModel->insertarAmo([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Alta->insertarAmo()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Alta))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-07 22:20:08 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\Proyecto_Topicos\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\Proyecto_Topicos\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\Proyecto_Topicos\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Proyecto_Topicos\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Proyecto_Topicos\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `am...', Array, false)
#4 C:\xampp\htdocs\Proyecto_Topicos\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Proyecto_Topicos\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Proyecto_Topicos\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Proyecto_Topicos\app\Models\AmoModel.php(19): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\Proyecto_Topicos\app\Controllers\Alta.php(48): App\Models\AmoModel->insertarAmo(Array)
#9 C:\xampp\htdocs\Proyecto_Topicos\system\CodeIgniter.php(933): App\Controllers\Alta->insertarAmo()
#10 C:\xampp\htdocs\Proyecto_Topicos\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Alta))
#11 C:\xampp\htdocs\Proyecto_Topicos\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\Proyecto_Topicos\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\Proyecto_Topicos\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\Proyecto_Topicos\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\Proyecto_Topicos\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\Proyecto_Topicos\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Proyecto_Topicos\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Proyecto_Topicos\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `am...', Array, false)
#3 C:\xampp\htdocs\Proyecto_Topicos\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\Proyecto_Topicos\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\Proyecto_Topicos\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp\htdocs\Proyecto_Topicos\app\Models\AmoModel.php(19): CodeIgniter\Model->insert(Array)
#7 C:\xampp\htdocs\Proyecto_Topicos\app\Controllers\Alta.php(48): App\Models\AmoModel->insertarAmo(Array)
#8 C:\xampp\htdocs\Proyecto_Topicos\system\CodeIgniter.php(933): App\Controllers\Alta->insertarAmo()
#9 C:\xampp\htdocs\Proyecto_Topicos\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Alta))
#10 C:\xampp\htdocs\Proyecto_Topicos\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Proyecto_Topicos\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Proyecto_Topicos\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\Proyecto_Topicos\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-05-07 22:20:08 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: POST, Route: insertarAmo]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `amos` (`nombre`, `apellido`, `direccion`, `telefono`, `fechaAlta`) VALUES (:nombre:, :apellido:, :direccion:, :telefono:, :fechaAlta:)', [...], false)
 3 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Models\AmoModel.php(19): CodeIgniter\Model->insert([...])
 7 APPPATH\Controllers\Alta.php(48): App\Models\AmoModel->insertarAmo([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Alta->insertarAmo()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Alta))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-07 22:21:09 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\Proyecto_Topicos\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\Proyecto_Topicos\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\Proyecto_Topicos\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Proyecto_Topicos\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Proyecto_Topicos\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `am...', Array, false)
#4 C:\xampp\htdocs\Proyecto_Topicos\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Proyecto_Topicos\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Proyecto_Topicos\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Proyecto_Topicos\app\Models\AmoModel.php(19): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\Proyecto_Topicos\app\Controllers\Alta.php(48): App\Models\AmoModel->insertarAmo(Array)
#9 C:\xampp\htdocs\Proyecto_Topicos\system\CodeIgniter.php(933): App\Controllers\Alta->insertarAmo()
#10 C:\xampp\htdocs\Proyecto_Topicos\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Alta))
#11 C:\xampp\htdocs\Proyecto_Topicos\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\Proyecto_Topicos\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\Proyecto_Topicos\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\Proyecto_Topicos\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\Proyecto_Topicos\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\Proyecto_Topicos\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Proyecto_Topicos\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Proyecto_Topicos\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `am...', Array, false)
#3 C:\xampp\htdocs\Proyecto_Topicos\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\Proyecto_Topicos\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\Proyecto_Topicos\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp\htdocs\Proyecto_Topicos\app\Models\AmoModel.php(19): CodeIgniter\Model->insert(Array)
#7 C:\xampp\htdocs\Proyecto_Topicos\app\Controllers\Alta.php(48): App\Models\AmoModel->insertarAmo(Array)
#8 C:\xampp\htdocs\Proyecto_Topicos\system\CodeIgniter.php(933): App\Controllers\Alta->insertarAmo()
#9 C:\xampp\htdocs\Proyecto_Topicos\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Alta))
#10 C:\xampp\htdocs\Proyecto_Topicos\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Proyecto_Topicos\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Proyecto_Topicos\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\Proyecto_Topicos\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-05-07 22:21:09 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: POST, Route: insertarAmo]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `amos` (`nombre`, `apellido`, `direccion`, `telefono`, `fechaAlta`) VALUES (:nombre:, :apellido:, :direccion:, :telefono:, :fechaAlta:)', [...], false)
 3 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Models\AmoModel.php(19): CodeIgniter\Model->insert([...])
 7 APPPATH\Controllers\Alta.php(48): App\Models\AmoModel->insertarAmo([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Alta->insertarAmo()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Alta))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-07 22:24:45 --> mysqli_sql_exception: Unknown column 'apellido' in 'field list' in C:\xampp\htdocs\Proyecto_Topicos\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\Proyecto_Topicos\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `am...', 0)
#1 C:\xampp\htdocs\Proyecto_Topicos\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `am...')
#2 C:\xampp\htdocs\Proyecto_Topicos\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `am...')
#3 C:\xampp\htdocs\Proyecto_Topicos\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `am...', Array, false)
#4 C:\xampp\htdocs\Proyecto_Topicos\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Proyecto_Topicos\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Proyecto_Topicos\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Proyecto_Topicos\app\Models\AmoModel.php(19): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\Proyecto_Topicos\app\Controllers\Alta.php(48): App\Models\AmoModel->insertarAmo(Array)
#9 C:\xampp\htdocs\Proyecto_Topicos\system\CodeIgniter.php(933): App\Controllers\Alta->insertarAmo()
#10 C:\xampp\htdocs\Proyecto_Topicos\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Alta))
#11 C:\xampp\htdocs\Proyecto_Topicos\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\Proyecto_Topicos\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\Proyecto_Topicos\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\Proyecto_Topicos\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-05-07 22:24:45 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'apellido' in 'field list'
[Method: POST, Route: insertarAmo]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `amos` (`nombre`, `apellido`, `direccion`, `telefono`, `fechaAlta`) VALUES (:nombre:, :apellido:, :direccion:, :telefono:, :fechaAlta:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Models\AmoModel.php(19): CodeIgniter\Model->insert([...])
 6 APPPATH\Controllers\Alta.php(48): App\Models\AmoModel->insertarAmo([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Alta->insertarAmo()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Alta))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 22:24:45 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'apellido' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `amos` (`nombre`, `apellido`, `direccion`, `telefono`, `fechaAlta`) VALUES (\'asdasd\', \'asdasdsa\', \'asdsad\', \'123213\', \'2025-05-15\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `amos` (`nombre`, `apellido`, `direccion`, `telefono`, `fechaAlta`) VALUES (\'asdasd\', \'asdasdsa\', \'asdsad\', \'123213\', \'2025-05-15\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `amos` (`nombre`, `apellido`, `direccion`, `telefono`, `fechaAlta`) VALUES (:nombre:, :apellido:, :direccion:, :telefono:, :fechaAlta:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Models\AmoModel.php(19): CodeIgniter\Model->insert([...])
 8 APPPATH\Controllers\Alta.php(48): App\Models\AmoModel->insertarAmo([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Alta->insertarAmo()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Alta))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 22:24:45 --> [Caused by] mysqli_sql_exception: Unknown column 'apellido' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `amos` (`nombre`, `apellido`, `direccion`, `telefono`, `fechaAlta`) VALUES (\'asdasd\', \'asdasdsa\', \'asdsad\', \'123213\', \'2025-05-15\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `amos` (`nombre`, `apellido`, `direccion`, `telefono`, `fechaAlta`) VALUES (\'asdasd\', \'asdasdsa\', \'asdsad\', \'123213\', \'2025-05-15\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `amos` (`nombre`, `apellido`, `direccion`, `telefono`, `fechaAlta`) VALUES (\'asdasd\', \'asdasdsa\', \'asdsad\', \'123213\', \'2025-05-15\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `amos` (`nombre`, `apellido`, `direccion`, `telefono`, `fechaAlta`) VALUES (:nombre:, :apellido:, :direccion:, :telefono:, :fechaAlta:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Models\AmoModel.php(19): CodeIgniter\Model->insert([...])
 9 APPPATH\Controllers\Alta.php(48): App\Models\AmoModel->insertarAmo([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Alta->insertarAmo()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Alta))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
